version: "3.4"

services:
  web: &web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    stdin_open: true

  build:
    <<: *web
    ports: []
    command: yarn run build
